### Recuperar todos los escenarios básicos
GET http://localhost:1234/basic

### Recuperar todos los escenarios extendidos
GET http://localhost:1234/extended

### Procesar un escenario básico
POST http://localhost:1234/basic
Content-Type: application/json

{
  "titulo": "The maze runner",
  "numeroActores": 3,
  "actores": ["Dylan", "Ki", "Kaya"],
  "numeroEscenas": 6,
  "participacion": [
    [0, 1, 0, 1, 0, 1],
    [1, 0, 1, 1, 0, 0],
    [0, 1, 0, 0, 1, 0]
  ],
  "precioHora": [3, 5, 7],
  "duracionEscenas": [1, 2, 3, 4, 5, 6],
  "ordenEscenas": [1, 2, 3, 4, 5, 6]
}

### Procesar un escenario extendido
POST http://localhost:1234/extended
Content-Type: application/json

{
  "titulo": "The maze runner",
  "numeroActores": 3,
  "actores": ["Dylan", "Ki", "Kaya"],
  "numeroEscenas": 6,
  "participacion": [
    [0, 1, 0, 1, 0, 1],
    [1, 0, 1, 1, 0, 0],
    [0, 1, 0, 0, 1, 0]
  ],
  "precioHora": [3, 5, 7],
  "duracionEscenas": [1, 2, 3, 4, 5, 6],
  "ordenEscenas": [1, 2, 3, 4, 5, 6],
  "disponibilidadActores":[0, 0, 0],
  "parejas":[["Dylan","Ki"]]
}